# Generated by Django 3.1.1 on 2020-09-12 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('tab_number', models.IntegerField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=128)),
                ('education', models.CharField(max_length=256)),
                ('experience', models.TextField()),
            ],
            options={
                'ordering': ('-fio',),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_stop', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.person')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.position')),
            ],
            options={
                'unique_together': {('person', 'position')},
            },
        ),
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.ManyToManyField(through='staff.Staff', to='staff.Position'),
        ),
    ]
