# Generated by Django 3.1.1 on 2020-09-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0001_initial'),
        ('staff', '0002_auto_20200912_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='competence_category',
            field=models.ManyToManyField(related_name='positions', to='competencies.Category'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.ManyToManyField(related_name='persons', through='staff.Staff', to='staff.Position'),
        ),
    ]
