# Generated by Django 3.1.1 on 2020-10-04 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20200920_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='staff.department'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='department',
        ),
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.ManyToManyField(related_name='workers', through='staff.Staff', to='staff.Department'),
        ),
    ]
