# Generated by Django 3.1.5 on 2021-01-24 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0003_auto_20210124_0404'),
        ('staff', '0005_auto_20201004_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел', 'verbose_name_plural': 'Список отделов'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('-fio',), 'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Список должностей'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ('-date_start',), 'verbose_name': 'Штат сотрудников', 'verbose_name_plural': 'Штат сотрудников'},
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Наименование отдела'),
        ),
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.ManyToManyField(related_name='workers', through='staff.Staff', to='staff.Department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='person',
            name='education',
            field=models.CharField(max_length=256, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='person',
            name='experience',
            field=models.TextField(verbose_name='Опыт сотрудника'),
        ),
        migrations.AlterField(
            model_name='person',
            name='fio',
            field=models.CharField(max_length=128, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.ManyToManyField(related_name='persons', through='staff.Staff', to='staff.Position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tab_number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Табельный номер'),
        ),
        migrations.AlterField(
            model_name='position',
            name='competence_category',
            field=models.ManyToManyField(related_name='positions', to='competencies.Category', verbose_name='Категория компетенций'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Наименование должности'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_start',
            field=models.DateField(verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_stop',
            field=models.DateField(blank=True, null=True, verbose_name='Окончание работы'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='staff.department', verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.person', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.position', verbose_name='Должность'),
        ),
    ]
