# Generated by Django 3.1.5 on 2021-01-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20210124_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=45, unique=True, verbose_name='Наименование должности'),
        ),
    ]
