# Generated by Django 3.1.6 on 2021-02-10 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20210209_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='staff.person', verbose_name='Наставник'),
        ),
    ]
