# Generated by Django 3.1.6 on 2021-02-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_person_mentor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='employment_form',
            field=models.IntegerField(choices=[(1, 'Офисная'), (2, 'Гибридная'), (3, 'Удаленная')], default=1, verbose_name='Форма занятости'),
        ),
        migrations.AlterField(
            model_name='person',
            name='status',
            field=models.IntegerField(choices=[(1, 'Испытательный срок'), (2, 'Работа')], default=2, verbose_name='Статус работы'),
        ),
    ]
