# Generated by Django 3.1.6 on 2021-02-11 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20210210_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_staff', to='staff.person', verbose_name='Сотрудник'),
        ),
    ]
