# Generated by Django 3.1.6 on 2021-03-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0015_auto_20210314_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='institution',
            field=models.TextField(blank=True, null=True, verbose_name='Учебное заведение'),
        ),
    ]
