# Generated by Django 3.1.6 on 2021-05-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_person_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='experience',
            field=models.TextField(blank=True, null=True, verbose_name='Опыт сотрудника'),
        ),
    ]
