# Generated by Django 3.1.1 on 2020-10-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='name',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
