# Generated by Django 3.1.6 on 2021-04-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0004_auto_20210331_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competence',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
    ]
