# Generated by Django 3.1.6 on 2021-11-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0005_auto_20210411_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='level_0',
            field=models.TextField(blank=True, null=True, verbose_name='Уровень 0'),
        ),
        migrations.AddField(
            model_name='competence',
            name='level_1',
            field=models.TextField(blank=True, null=True, verbose_name='Уровень 1'),
        ),
        migrations.AddField(
            model_name='competence',
            name='level_2',
            field=models.TextField(blank=True, null=True, verbose_name='Уровень 2'),
        ),
        migrations.AddField(
            model_name='competence',
            name='level_3',
            field=models.TextField(blank=True, null=True, verbose_name='Уровень 3'),
        ),
    ]
