# Generated by Django 3.1.1 on 2020-09-12 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencies', '0001_initial'),
        ('staff', '0003_auto_20200912_2310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence_val', models.SmallIntegerField(choices=[('0', 'Отсутствие или не актуальна'), ('1', 'Владение на  проф. уровне'), ('2', 'Среднее'), ('3', 'Слабо выражена')], default=0, max_length=1)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competencies.competence')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='competencies',
            field=models.ManyToManyField(related_name='questionnaires', through='questionnaires.QuestionnaireRow', to='competencies.Competence'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='staff.person'),
        ),
    ]
