# Generated by Django 3.1.1 on 2020-09-20 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairerow',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='questionnairerow',
            name='competence_val',
            field=models.SmallIntegerField(choices=[(0, 'Отсутствие или не актуальна'), (1, 'Слабо выражена'), (2, 'Среднее'), (3, 'Владение на  проф. уровне')], default=0),
        ),
        migrations.CreateModel(
            name='QuestionnaireRowHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence_val', models.SmallIntegerField(choices=[(0, 'Отсутствие или не актуальна'), (1, 'Слабо выражена'), (2, 'Среднее'), (3, 'Владение на  проф. уровне')], default=0)),
                ('date', models.DateField()),
                ('questionnaire_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='questionnaires.questionnairerow')),
            ],
        ),
    ]
