# Generated by Django 3.1.1 on 2020-09-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_auto_20200920_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairerow',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
