# Generated by Django 3.1.5 on 2021-01-25 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0005_auto_20210124_0404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnairerowhistory',
            options={'ordering': ('-date',)},
        ),
        migrations.AddField(
            model_name='questionnairerowhistory',
            name='new_competence_val',
            field=models.SmallIntegerField(choices=[(0, 'Отсутствует или не актуальна'), (1, 'Слабо выражена'), (2, 'Среднее владение'), (3, 'Владение на проф. уровне')], default=0),
        ),
        migrations.AlterField(
            model_name='questionnairerowhistory',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
