# Generated by Django 3.1.6 on 2021-03-08 16:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0013_auto_20210212_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dev_plan', to='staff.person', verbose_name='План развития')),
            ],
        ),
        migrations.CreateModel(
            name='PlanActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(max_length=255, verbose_name='Развитие ПТЗН/Ценности')),
                ('method', models.CharField(max_length=255, verbose_name='Метод развития')),
                ('required_up_to', models.DateField(verbose_name='Требуется до')),
                ('activity', models.CharField(max_length=255, verbose_name='Планируемая активность')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_activities', to='development_plan.developmentplan')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values', models.CharField(max_length=255, verbose_name='Развитие ПТЗН/Ценности')),
                ('activity_type', models.PositiveIntegerField(choices=[(1, 'Электронное обучение')], verbose_name='Тип активности')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('hours', models.FloatField(help_text='Кол-во академических часов', validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Объем')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Начато (запланировано)')),
                ('stop', models.DateField(blank=True, null=True, verbose_name='Завершено')),
                ('required_up_to', models.DateField(blank=True, null=True, verbose_name='Требуется до')),
                ('status', models.PositiveIntegerField(blank=True, choices=[(0, 'Не утверждено'), (1, 'На рассмотрении'), (2, 'Утверждено')], null=True, verbose_name='Статус')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Причина не выполнениня')),
                ('activity_status', models.PositiveIntegerField(blank=True, choices=[(0, 'Не выполненные'), (1, 'Запланированные'), (2, 'Выполненные')], null=True, verbose_name='Статус активности')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='development_plan.developmentplan')),
            ],
        ),
    ]
