# Generated by Django 3.1.6 on 2021-03-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('development_plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developmentplan',
            options={'verbose_name': 'Индивидуальный план развития', 'verbose_name_plural': 'Индивидуальные планы развития'},
        ),
    ]
