# Generated by Django 3.1.6 on 2021-03-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development_plan', '0002_auto_20210308_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_status',
            field=models.PositiveIntegerField(choices=[(0, 'Не выполненные'), (1, 'Запланированные'), (2, 'Выполненные')], verbose_name='Статус активности'),
        ),
    ]
