# Generated by Django 3.1.6 on 2021-03-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development_plan', '0003_auto_20210308_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='values',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Развитие ПТЗН/Ценности'),
        ),
    ]
