# Generated by Django 3.1.6 on 2021-03-14 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_auto_20210212_0055'),
        ('development_plan', '0004_auto_20210308_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developmentplan',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dev_plan', to='staff.person', verbose_name='Сотрудник'),
        ),
    ]
