# Generated by Django 3.1.6 on 2021-02-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0012_auto_20210210_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirstChapterMapPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255, verbose_name='Поставленная задача')),
                ('period_of_execution', models.CharField(max_length=50, verbose_name='Срок исполнения')),
                ('status', models.IntegerField(choices=[(1, 'В работе'), (2, 'На проверке'), (3, 'Завершена')], default=1, verbose_name='Статус выполнения')),
                ('execution_date', models.DateField(verbose_name='Дата исполнения')),
                ('extra_info', models.TextField(verbose_name='Необходимая информация,  документы и т.д. для выполнения')),
                ('pattern', models.BooleanField(default=True, verbose_name='Является шаблоном')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание и комментарии')),
                ('extra_fields', models.JSONField(blank=True, null=True, verbose_name='Дополнительные поля')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map', to='staff.person', verbose_name='Карта адаптации')),
            ],
        ),
        migrations.CreateModel(
            name='MapPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование пункта')),
                ('point_type', models.IntegerField(choices=[(1, 'Руководитель'), (2, 'Рядовой сотрудник')], default=1, verbose_name='Тип должности')),
                ('stage_number', models.IntegerField(verbose_name='Номер этапа')),
            ],
        ),
        migrations.CreateModel(
            name='MapPointValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(verbose_name='Занчение пункта')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_values', to='adaptation.map', verbose_name='Карта адаптации')),
                ('map_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_values', to='adaptation.mappoint', verbose_name='Карта адаптации')),
            ],
        ),
        migrations.AddField(
            model_name='mappoint',
            name='maps',
            field=models.ManyToManyField(related_name='map_points', through='adaptation.MapPointValue', to='adaptation.Map', verbose_name='Карты адаптаций'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='positions',
            field=models.ManyToManyField(related_name='map_points', to='staff.Position', verbose_name='Должность'),
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('type', models.IntegerField(choices=[(1, 'Файл'), (2, 'Ссылка')], verbose_name='Тип информации')),
                ('path', models.CharField(max_length=255, verbose_name='Путь к информации')),
                ('map_point_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_files', to='adaptation.mappointvalue', verbose_name='Пункт')),
            ],
        ),
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Итоговое'), (2, 'HR'), (3, 'Руководитель'), (4, 'Наставник')], verbose_name='Тип заключения')),
                ('comment', models.TextField(verbose_name='Комментарий')),
                ('final_value', models.IntegerField(choices=[(1, 'ИС успешно завершен'), (2, 'Продлить АП'), (3, 'ИС не пройден'), (4, 'Рекомендовать досрочно завершить ИС')], default=1, verbose_name='Заключение')),
                ('adaptation_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusions', to='adaptation.map', verbose_name='Карта адаптации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusions', to='staff.person', verbose_name='Автор заключения')),
            ],
        ),
    ]
