# Generated by Django 3.1.6 on 2021-02-11 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_auto_20210212_0055'),
        ('adaptation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirstChapterMapPoint',
        ),
        migrations.AlterField(
            model_name='map',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map', to='staff.person', verbose_name='Сотрудник'),
        ),
    ]
