# Generated by Django 3.1.6 on 2021-02-17 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation', '0002_auto_20210212_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conclusion',
            options={'verbose_name': 'Заключение', 'verbose_name_plural': 'Заключения'},
        ),
        migrations.AlterModelOptions(
            name='extrainfo',
            options={'verbose_name': 'Дополнительная информация', 'verbose_name_plural': 'Дополнительная информация'},
        ),
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ('employee__person_staff__date_start',), 'verbose_name': 'Карта адаптации', 'verbose_name_plural': 'Карты адаптаций'},
        ),
        migrations.AlterModelOptions(
            name='mappoint',
            options={'verbose_name': 'Пункт карты адаптации', 'verbose_name_plural': 'Пункты карт адаптаций'},
        ),
        migrations.AlterModelOptions(
            name='mappointvalue',
            options={'verbose_name': 'Значение пункта карты адаптации', 'verbose_name_plural': 'Значения пунктов карт адаптаций'},
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='point_type',
            field=models.IntegerField(choices=[(1, 'Все сотрудники'), (2, 'Руководитель'), (3, 'Рядовой сотрудник')], default=1, verbose_name='Тип должности'),
        ),
    ]
