# Generated by Django 3.1.6 on 2021-02-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation', '0004_remove_mappoint_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='stage_number',
            field=models.PositiveIntegerField(verbose_name='Номер этапа'),
        ),
    ]
