# Generated by Django 3.1.6 on 2021-02-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation', '0005_auto_20210217_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='form_of_employment',
            field=models.PositiveIntegerField(choices=[(1, 'Офисная'), (2, 'Гибридная'), (3, 'Удаленная')], default=1, verbose_name='Форма занятости'),
        ),
    ]
