# Generated by Django 3.1.6 on 2021-02-17 14:12

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation', '0006_mappoint_form_of_employment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mappoint',
            name='form_of_employment',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Офисная'), (2, 'Гибридная'), (3, 'Удаленная')], max_length=5, verbose_name='Форма занятости'),
        ),
    ]
