# Generated by Django 3.1.6 on 2021-02-24 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation', '0008_auto_20210224_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mappoint',
            options={'ordering': ('pk',), 'verbose_name': 'Пункт карты адаптации', 'verbose_name_plural': 'Пункты карт адаптаций'},
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='period_of_execution',
            field=models.PositiveIntegerField(blank=True, help_text='Количество рабочих дней', null=True, verbose_name='Срок исполнения'),
        ),
        migrations.AlterField(
            model_name='mappointvalue',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_point_values', to='adaptation.map', verbose_name='Карта адаптации'),
        ),
    ]
