# Generated by Django 3.1.6 on 2021-02-27 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation', '0009_auto_20210224_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappointvalue',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование пункта'),
        ),
        migrations.AlterField(
            model_name='mappointvalue',
            name='map_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='point_values', to='adaptation.mappoint', verbose_name='Карта адаптации'),
        ),
    ]
