# Generated by Django 3.1.6 on 2021-02-28 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation', '0010_auto_20210227_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrainfo',
            name='path',
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='extra_info_file',
            field=models.FileField(blank=True, null=True, upload_to='extra_info', verbose_name='Файл'),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
