# Generated by Django 3.1.6 on 2021-03-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation', '0011_auto_20210228_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappointvalue',
            name='stage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Этап'),
        ),
    ]
