# Generated by Django 3.1.6 on 2021-03-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0003_auto_20210124_0404'),
        ('adaptation', '0012_mappointvalue_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappointvalue',
            name='competence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='map_point_values', to='competencies.competence', verbose_name='Компетенция'),
        ),
    ]
