# Generated by Django 3.1.6 on 2021-03-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adaptation', '0013_mappointvalue_competence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conclusion',
            name='type',
            field=models.IntegerField(choices=[(1, 'Наставник'), (2, 'Руководитель'), (3, 'HR'), (4, 'Итоговое')], verbose_name='Тип заключения'),
        ),
    ]
