# Generated by Django 3.1.5 on 2021-01-24 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0006_auto_20210124_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование продукта')),
                ('city', models.CharField(max_length=25, verbose_name='Город')),
                ('description', models.TextField(verbose_name='Описание продукта')),
                ('additional_info', models.TextField(verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Список продуктов',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование проекта')),
                ('region', models.CharField(max_length=50, verbose_name='Регион')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('additional_info', models.TextField(verbose_name='Дополнительная информация')),
                ('persons', models.ManyToManyField(related_name='projects', to='staff.Person', verbose_name='Сотрудники')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Список проектов',
                'ordering': ('name',),
            },
        ),
    ]
